x-logging: &default-logging
  driver: loki
  options:
    loki-url: https://120909:eyJrIjoiMmJjNTAwYmI1MWM1NTMwYmIyMjY1YWRjZGUxNDRhMzAzZmE2MTAxMSIsIm4iOiJzYW5kYm94IiwiaWQiOjUxOTM4MX0=@logs-prod-eu-west-0.grafana.net/loki/api/v1/push
    labels: namespace
    loki-relabel-config: |
      - action: replace
        source_labels: ["namespace","compose_service"]
        separator: "/"
        target_label: job
      - action: replace
        source_labels: ["container_name"]
        target_label: instance

version: '3.4'
volumes:
  mongodb-vol:

services:
  agent:
    profiles: ["tnsapp","agent","mongo"]
    image: grafana/agent:latest
    volumes:
      - ./config:/etc/agent-config
      - /var/log:/var/log
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/agent.yaml
      - -prometheus.wal-directory=/tmp/agent/wal
    ports:
      - "12345:12345"
    logging: *default-logging
  db:
    profiles: ["tnsapp"]
    image: grafana/tns-db:latest
    command:
      - '-log.level=debug'
    ports:
      - 0.0.0.0:8000:80
    labels:
      namespace: tns
    logging: *default-logging

  app:
    profiles: ["tnsapp"]
    image: grafana/tns-app:latest
    command:
      - '-log.level=debug'
      - 'http://db'
    links:
      - db
    ports:
      - 0.0.0.0:8001:80
    labels:
      namespace: tns
    logging: *default-logging

  loadgen:
    profiles: ["tnsapp"]
    image: grafana/tns-loadgen:latest
    command:
      - '-log.level=debug'
      - 'http://app'
    links:
      - app
    ports:
      - 0.0.0.0:8002:80
    labels:
      namespace: tns
    logging: *default-logging

  mongo:
    profiles: ["mongo"]
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb-vol:/data/db
    logging: *default-logging
